{% set version = "0.2.1" %}

package:
  name: warc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/warc/warc-{{ version }}.tar.gz
  sha256: 65ec3336287ae7a17c969736935ba188678df10f2ec813d8e3474cc51bb71d39

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3

test:
  imports:
    - warc

about:
  home: http://github.com/internetarchive/warc
  license: GPL 2.0
  license_file: LICENSE
  license_family: GPL2
  summary: 'Python library to work with ARC and WARC files'
  doc_url: https://warc.readthedocs.io/en/latest/
  dev_url: http://github.com/internetarchive/warc

extra:
  recipe-maintainers:
    - pmlandwehr
