travis:
  secure:
    BINSTAR_TOKEN: iAGxAIFBqC9jr8aRLSEFnKGUz3Y8+oZNptpA6aPRX8h8JfIU79IdRZC+1if+XIfYY2jeGLXSb0pnuZbxAMEFSSyPx09MMVHLnE3psWRyrzg5vEsH71mHR3MKI5pKUccLB+VD2XrKa/5/kMUTaUin8kmCLeBkISYFO5p8WjO4tN0mCf2/IWXTfyR87MNxxP+6t7K+Ju2/koJD2hp+1/1R9H+YJN7aZbCBsi0Px8p1L2MOiD7836LOpWWFrypccy4dCKoTLb7/PJ8EdgDBvR6BOL+y7THb0z7I+Q+92wbAqHRD4Nk4YC7IzFsmosCt82IJJjqrCmRldomRPgdC01KLyqvqfOrA0qxKIofjUYucL/P59VpAeGMYXeaf/dJAyGCAwJ9tZGbHQ8ekKmv4RgM4PogEeJNGqsfTbPbrKHBkjRymVnXCojK9wQHWQoTYosRG7j9T2r+QIqGdKXVLSVj1pWJ2ZZeIS2JVF6jpZ56Y+8uJSB0qjHN+Myhwgq260V0eNbOsYAgkDlC6KGYTMgoTNR2jJJQInAdjMnooKlpnQsMuM2rnR3G+NaRgWCoYBk1wUSQsrvLIZgonSpLSNflkhvTwGhYc2ZjDV086BcQ/wN88nTWUqXyEzUkcjK8stYPmSXbpc2Q+ZgD5A1cZ65fzXjKSDQQFbiO2qp0YA4pdGUg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
