travis:
  secure:
    BINSTAR_TOKEN: C9TXgeXIsIlmS55rcM6qqvI3TgdpluGfkO169uvA2pGsiYgcq92sorsMvZ85g2AnNt3IYeNnd0K4gnDYD1HkEEoDUEh9zO2qkeCZk+gthpBqN5EYk+xrZC9SNf4k4EUCPmKVjVt22/Uwj3GzXKpqhWCXmKxuSXTiZ5lcn8VVzqmoHHo04gQi9DqWldRRae9XvtoFk4BFls35X1l7hF9rsd1qLCArbRMmQp070dUhOfbgbp1gthXBO/vQ1076P+eW3h5EztUyu41YH+TruNbgabHQFUiUdygBbvmxV+ERvSS3Jf+pyJ6xVOnBtrKajPqc9U0M4O8c314iBTvV5mx/AP3yVrKGcRv7kfKNysEPtRgZKRNewLD2cbPISgerrIp6vJrcjbzrtBgd81MzgK+UbHqrhx2K24gqLFtHTHYshOF+zw6J1BDD21kI3Z2/QiCGPQeyf/ZmzcfbjBKj1Cnn8comm8PKSmyX+W7bQMbFtDpKlChsiN6Xj3Wqg1y6yDSMPYZXHW4zIKAkeMfu6qsIpSCQq0DPfOrrZJgGZfBPwBYhUHXIhuolW9WNk7s6W4VXelGnUmrriNoxeCtQGdLoE1pckAGZ4MVNlk+nP16oJNHyJWYhnHI1oop0TRgU+9bX31K51z0/T+/0nx3A4cf+wG81pXEtKh1WTD/KJUuWeUg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
